// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/csherida/api-key-manager-service/internal/api-key-manager-service/api"
	"github.com/csherida/api-key-manager-service/internal/api-key-manager-service/infra"
	"github.com/csherida/api-key-manager-service/internal/api-key-manager-service/usecase"
)

// Injectors from wire_inject.go:

// SetupApplication is where we define the dependencies wire will inject
func SetupApplication() (Application, error) {
	context := NewContext()
	dataStore := infra.NewDataStore()
	apiKeyGeneration := usecase.NewApiKeyGeneration(dataStore)
	apiKeyGeneratorHandler := api.NewApiKeyGeneratorHandler(apiKeyGeneration)
	apiKeyValidation := usecase.NewApiKeyValidation(dataStore)
	apiKeyValidationHandler := api.NewApiKeyValidationHandler(apiKeyValidation)
	application := NewApplication(context, apiKeyGeneratorHandler, apiKeyValidationHandler)
	return application, nil
}
